import json


def build_prompt(
    text: str,
    schema: dict,
    page_num: int,
    total_pages: int,
    last_error: str | None = None,
    ocr_used: bool = False,
) -> str:
    schema_str = json.dumps(schema, indent=2)

    error_hint = ""
    if last_error:
        error_hint = f"\nYour last attempt produced this error: {last_error}\nPlease correct it.\n"

    ocr_hint = ""
    if ocr_used:
        ocr_hint = "\nThe text below was extracted via OCR from a scanned page and may contain recognition errors.\n"

    return f"""You are a data extraction assistant.

You are processing page {page_num + 1} of {total_pages}.
{error_hint}{ocr_hint}
Extract data from the text below according to the schema.
Follow field descriptions carefully.
Fields described as "summary" should be generated by you based on the content.
Return ONLY the values — no schema, no types, no explanations.

Example response:
{{"name": "Jane Smith", "date": "2024-01-01"}}

Schema:
{schema_str}

Text:
{text}

Respond with JSON only. Field names and values only.
"""
